<?php

/**
 * woocommerce environment bootstrap file
 *
 * @generated by function-mocker environment generation tool on 2018-07-14 09:34:24 (UTC)
 * @link https://github.com/lucatume/function-mocker
 */


require_once( __DIR__ . '/functions.php' );