<?php

/**
 * woocommerce environment bootstrap file
 *
 * @generated by function-mocker environment generation tool on 2018-08-07 06:50:32 (UTC)
 * @link https://github.com/lucatume/function-mocker
 */


require_once __DIR__ . '/functions.php';

class EnvAutoloader_woocommerce {

	protected static $classMap = [
		'WC_Abstract_Legacy_Product' =>  __DIR__ . '/WC_Abstract_Legacy_Product.php',
		'WC_Product' =>  __DIR__ . '/WC_Product.php',
		'WC_Data' =>  __DIR__ . '/WC_Data.php',
	];

	protected $rootDir;

	public function __construct( $rootDir ) {
		$this->rootDir = $rootDir;
	}

	public function autoload( $class ) {
		if ( array_key_exists( $class, static::$classMap ) ) {
			include_once static::$classMap[ $class ];

			return true;
		}

		return false;
	}
}

spl_autoload_register( [ new EnvAutoloader_woocommerce( __DIR__ ), 'autoload' ] );